'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import SidebarNext from '../components/next/SidebarNext';
import HeaderNext from '../components/next/HeaderNext';
import RightSidebarNext from '../components/next/RightSidebarNext';
import ScrollToTopButton from '../components/ScrollToTopButton';
import { useTheme } from '../ThemeContext';

const RAVELL_MARK_PATH = 'M12 12h42c17 0 28 10 28 26 0 14-8 22-20 26l22 24H69L48 66v12L29 88V43h21c7 0 11-3 11-8s-4-8-11-8H28z';

// Client shell for interactive navigation chrome; route content can still be
// statically generated by the server components under src/app.
export default function LayoutClient({ children }: { children: React.ReactNode }) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const menuButtonRef = useRef<HTMLButtonElement>(null);
  const { theme } = useTheme();

  useEffect(() => {
    const color = theme === 'dark' ? '#e6b47c' : '#8a5a25';
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path fill="${color}" d="${RAVELL_MARK_PATH}"/></svg>`;
    const favicon = `data:image/svg+xml,${encodeURIComponent(svg)}`;

    document
      .querySelectorAll<HTMLLinkElement>('link[rel="icon"], link[rel="shortcut icon"]')
      .forEach((link) => link.setAttribute('href', favicon));
  }, [theme]);

  useEffect(() => {
    const mediaQuery = window.matchMedia('(max-width: 767px)');
    const updateViewport = () => setIsMobile(mediaQuery.matches);

    updateViewport();
    mediaQuery.addEventListener('change', updateViewport);
    return () => mediaQuery.removeEventListener('change', updateViewport);
  }, []);

  const closeMenu = useCallback((restoreFocus = false) => {
    setIsMenuOpen(false);
    if (restoreFocus) {
      window.requestAnimationFrame(() => menuButtonRef.current?.focus());
    }
  }, []);

  useEffect(() => {
    if (!isMenuOpen) return;

    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') closeMenu(true);
    };

    document.addEventListener('keydown', closeOnEscape);
    return () => document.removeEventListener('keydown', closeOnEscape);
  }, [closeMenu, isMenuOpen]);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-gray-100 font-sans selection:bg-purple-500/30">
      <div className="flex w-full px-0">
        {/* Primary navigation sidebar */}
        <SidebarNext
          isMenuOpen={isMenuOpen}
          isMobile={isMobile}
          onClose={closeMenu}
          onNavigate={() => setIsMenuOpen(false)}
        />

        {/* Main route content */}
        <div className="flex-1 min-w-0 flex flex-col relative">
          <HeaderNext
            isMenuOpen={isMenuOpen}
            menuButtonRef={menuButtonRef}
            onOpenMenu={() => setIsMenuOpen(true)}
          />

          <div className="flex flex-1 min-w-0">
            <main className="flex-grow w-full px-4 sm:px-6 lg:px-8 py-6">
              {children}
            </main>

            {/* Contextual right sidebar */}
            <RightSidebarNext />
          </div>
        </div>
      </div>
      <ScrollToTopButton />
    </div>
  );
}
